version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    open-pull-requests-limit: 10

  # Terraform – bumps provider/plugins in main.tf
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  # Docker images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    open-pull-requests-limit: 10

  # Python (Poetry/pip)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    open-pull-requests-limit: 10

  # JavaScript (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
